name: Build & Push to Amazon ECR

on: 
  pull_request:
  push:
    branches-ignore:
      - stage
      - prod
    
permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable.yml
    with:
      ECR_INPUT: stl-challenge
    secrets: inherit