name: Deploy to Amazon ECS

on:
  push:
    branches: 
      - stage
      - prod
      
permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable.yml
    with:
      ECR_INPUT: stl-challenge
    secrets: inherit

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    needs: build

    steps:
    - name: Download AWS ECS Task Definition
      run: |
        aws ecs describe-task-definition --task-definition $NAMESPACE-$ENVIRONMENT --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ env.NAMESPACE }}-${{ env.ENVIRONMENT }}
        image: ${{ needs.build.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.NAMESPACE }}-${{ env.ENVIRONMENT }}
        cluster: ${{ env.NAMESPACE }}-${{ env.ENVIRONMENT }}
        wait-for-service-stability: true

# yaml-language-server: $schema=https://json.schemastore.org/github-action.json