name: Reduced pipeline (for non-stage/prod)

on: 
  pull_request:
  push:
    branches-ignore:
      - stage
      - prod
    
permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  NAMESPACE: stl-challenge
  ENVIRONMENT: ${{ github.ref_name }}

jobs:
  push:
    name: Push
    uses: ./.github/workflows/shared.yml
    with:
      ECR_INPUT: stl-challenge
      AWS_REGION: us-east-1
    secrets: inherit